/**
 * VYOMA API Server
 *
 * Express + Prisma + PostgreSQL backend.
 * Run: npm run dev (development) or npm start (production build).
 */
import "dotenv/config";
import path from "node:path";
import express from "express";
import cors from "cors";
import compression from "compression";

import villagesRouter from "./routes/villages.js";
import sitesRouter from "./routes/sites.js";
import dashboardRouter from "./routes/dashboard.js";
import adminRouter from "./routes/admin.js";
import {
  CACHE_MAX_AGE_SECONDS,
  CACHE_MAX_BODY_BYTES,
  cacheGet,
  cacheSet,
} from "./lib/responseCache.js";

const app = express();
const PORT = parseInt(process.env.PORT || "3001", 10);

// ---------------------------------------------------------------------------
// Tier-1 performance: gzip compression + in-memory GET response cache.
//
// The dataset behind every read endpoint is static — it only changes when the
// model exports are re-generated and `npm run seed` is re-run. Caching GET
// responses in RAM means the first request per URL hits Postgres and every
// repeat within the TTL is answered from memory (microseconds vs. a ~250 ms
// remote-DB round trip per request).
//
// Implementation lives in lib/responseCache.ts; the model-refresh job calls its
// clearResponseCache() when it finishes, so freshly re-seeded rows are served
// immediately without waiting out the TTL. The cache also self-expires after
// CACHE_MAX_AGE_SECONDS (default 5 minutes, env-overridable).
// ---------------------------------------------------------------------------

// Middleware — compression must be registered BEFORE the cache middleware so
// cached responses also pass through the gzip pipe.
app.use(cors());
app.use(express.json());
app.use(compression());

// ---------------------------------------------------------------------------
// Tier-3 static read bundles.
//
// The big village/site datasets are static between model runs, so they are
// pre-built into versioned JSON files (scripts/generate_frontend_static.py) and
// served here as plain files — the browser fetches each model version once
// (`Cache-Control: immutable`) and the database is never queried for the first
// page load. `../data/processed/static` resolves from the backend/ working dir;
// override with STATIC_DATA_DIR for other layouts.
// ---------------------------------------------------------------------------
const STATIC_ROOT = process.env.STATIC_DATA_DIR
  ? path.resolve(process.env.STATIC_DATA_DIR)
  : path.resolve(process.cwd(), "..", "data", "processed", "static");
app.use(
  "/static",
  express.static(STATIC_ROOT, {
    index: false,
    // latest.json is the discovery pointer (see scripts/generate_frontend_static.py):
    // it names the current bundle files, whose filenames embed the model run's
    // predicted_at. It must NEVER be cached — a browser holding a stale pointer
    // would keep fetching the old (immutable-cached) bundle after a refresh.
    // The versioned bundles themselves stay immutable in production (each model
    // run has a unique filename, so a new run = new URL = fresh download); in
    // development they are regenerated by hand, so force revalidation there.
    setHeaders: (res, filePath) => {
      if (filePath.endsWith("latest.json")) {
        res.setHeader("Cache-Control", "public, no-store");
      } else if (process.env.NODE_ENV === "production") {
        res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
      } else {
        res.setHeader("Cache-Control", "public, max-age=0, must-revalidate");
      }
    },
  })
);

/**
 * Cache middleware — must run BEFORE the route handlers so it can wrap res.json.
 */
app.use((req, res, next) => {
  // Only cache successful GETs. Skip the health check (live timestamp) and
  // every /api/admin path (the refresh job + status must never be cached).
  if (
    req.method !== "GET" ||
    req.originalUrl.startsWith("/api/health") ||
    req.originalUrl.startsWith("/api/admin")
  ) {
    next();
    return;
  }

  const key = req.originalUrl; // full path + query string

  const hit = cacheGet(key);
  if (hit !== undefined) {
    res.set("X-Cache", "HIT");
    res.set("Cache-Control", `public, max-age=${CACHE_MAX_AGE_SECONDS}`);
    res.set("Content-Type", "application/json; charset=utf-8");
    res.send(hit);
    return;
  }

  const originalJson = res.json.bind(res);

  res.json = ((body: unknown) => {
    if (res.statusCode >= 200 && res.statusCode < 400) {
      let payload: string;
      try {
        payload = JSON.stringify(body);
      } catch {
        payload = JSON.stringify({ error: "Failed to serialize response" });
      }
      if (payload.length <= CACHE_MAX_BODY_BYTES) cacheSet(key, payload);
      res.set("Cache-Control", `public, max-age=${CACHE_MAX_AGE_SECONDS}`);
      res.set("X-Cache", "MISS");
      res.set("Content-Type", "application/json; charset=utf-8");
      res.send(payload);
      return res;
    }
    // Errors are never cached — pass through untouched.
    return originalJson(body);
  }) as typeof res.json;

  next();
});

// Routes
app.use("/api/villages", villagesRouter);
app.use("/api/sites", sitesRouter);
app.use("/api/dashboard", dashboardRouter);
app.use("/api/admin", adminRouter); // POST /refresh — run the model refresh chain

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// 404 for unmatched routes
app.use((_req, res) => {
  res.status(404).json({ error: "Not found" });
});

app.listen(PORT, () => {
  console.log(`\n  VYOMA API server running at http://localhost:${PORT}\n`);
  console.log("  Routes:");
  console.log("    GET /api/villages          — list villages");
  console.log("    GET /api/villages/:id      — single village");
  console.log("    GET /api/sites             — list relocation sites");    console.log("    GET /api/sites/:id         — single site");
    console.log("    GET /api/dashboard         — aggregate stats");
    console.log("    GET /api/health            — health check");
    console.log("    POST /api/admin/refresh    — run the model refresh job");
    console.log("    GET /api/admin/refresh/status — job progress");
    console.log(`    GET /static/...            — versioned static data bundles (${STATIC_ROOT})`);
  console.log(`  Perf: gzip on · GET cache on (${CACHE_MAX_AGE_SECONDS}s TTL)\n`);
});
