/**
 * Seed script — loads the model's VYOMA export JSONs into PostgreSQL.
 *
 * Sources (generated by the model pipeline, NOT mock data):
 *   - data/processed/vyoma_export_all_states.json          → Village table (43,996 rows)
 *   - data/processed/vyoma_sites_export_all_states.json    → RelocationSite table (12,211 rows)
 *
 * The exports already match the VYOMA Village/RelocationSite interfaces field-for-field.
 * The only translation performed here is the relocation-priority vocabulary:
 * the model emits SHORT_TERM / MEDIUM_TERM / MONITOR, while the VYOMA UI expects
 * SHORT-TERM / MEDIUM-TERM / ROUTINE (see dashboard.ts + PriorityPage kanban lanes).
 *
 * Strategy: SNAPSHOT reload — tables are cleared and rebuilt from the JSONs in
 * chunked createMany batches. This is the right model for full generated exports
 * (43k+ rows): a per-row upsert loop over a remote database takes hours, while
 * chunked bulk inserts finish in seconds-to-minutes. The JSONs are the source of
 * truth; any row present in the DB but absent from the files is stale by design.
 *
 * Usage:  npm run seed
 * Env overrides (optional):
 *   DATABASE_URL            — required, real Postgres connection string
 *   SEED_DATA_DIR           — directory holding the two JSONs (default: ../../data/processed)
 *   SEED_VILLAGES_FILE      — villages filename (default vyoma_export_all_states.json)
 *   SEED_SITES_FILE         — sites filename (default vyoma_sites_export_all_states.json)
 */
import "dotenv/config"; // loads DATABASE_URL from .env (Prisma's runtime client does not)
import { PrismaClient } from "@prisma/client";
import { readFileSync, existsSync } from "fs";
import { resolve } from "path";

const prisma = new PrismaClient();

/** Map the model's relocation-priority vocabulary onto the VYOMA UI taxonomy. */
function toVyomaPriority(value: string): string {
  switch (value) {
    case "SHORT_TERM":
      return "SHORT-TERM";
    case "MEDIUM_TERM":
      return "MEDIUM-TERM";
    case "MONITOR":
      return "ROUTINE";
    default:
      return value; // IMMEDIATE (and any future values) pass through unchanged
  }
}

interface TopFactor {
  feature: string;
  value: string;
  impact: "high" | "medium" | "low";
}

interface Infrastructure {
  water_supply: boolean;
  electricity: boolean;
  road_access: boolean;
  shelter: boolean;
  medical_facility: boolean;
  sanitation: boolean;
}

const BATCH_SIZE = 5000;

/** Insert rows in chunked createMany batches (far faster than per-row upserts). */
async function bulkCreate(model: any, rows: any[], label: string) {
  for (let start = 0; start < rows.length; start += BATCH_SIZE) {
    const chunk = rows.slice(start, start + BATCH_SIZE);
    await model.createMany({ data: chunk });
    console.log(`  ... ${Math.min(start + BATCH_SIZE, rows.length)}/${rows.length} ${label}`);
  }
}

async function main() {
  const dataDir = process.env.SEED_DATA_DIR
    ? resolve(process.env.SEED_DATA_DIR)
    : resolve(import.meta.dirname, "../../data/processed");
  const villagesFile = resolve(
    dataDir,
    process.env.SEED_VILLAGES_FILE ?? "vyoma_export_all_states.json"
  );
  const sitesFile = resolve(
    dataDir,
    process.env.SEED_SITES_FILE ?? "vyoma_sites_export_all_states.json"
  );

  for (const f of [villagesFile, sitesFile]) {
    if (!existsSync(f)) {
      throw new Error(
        `Missing export file: ${f}\n` +
          `  Generate it first from the SIH2026 repo root:\n` +
          `    python scripts/generate_vyoma_export.py            (writes vyoma_export_all_states.json)\n` +
          `    python scripts/generate_relocation_sites.py        (writes vyoma_sites_export_all_states.json)\n` +
          `  or point SEED_DATA_DIR at a directory containing both files.`
      );
    }
  }

  // --- Snapshot reload: clear both tables first ---
  console.log("Clearing existing rows (snapshot reload)...");
  await prisma.relocationSite.deleteMany({});
  await prisma.village.deleteMany({});

  // --- Seed Villages ---
  const villagesRaw = readFileSync(villagesFile, "utf-8");
  const villages: any[] = JSON.parse(villagesRaw);

  console.log(`Loading ${villages.length} villages from ${villagesFile}...`);

  const vocabTranslated: Record<string, number> = {};
  const villageRows = villages.map((v) => {
    const priority = toVyomaPriority(v.relocation_priority);
    if (priority !== v.relocation_priority) {
      vocabTranslated[v.relocation_priority] =
        (vocabTranslated[v.relocation_priority] ?? 0) + 1;
    }
    return {
      village_id: v.village_id,
      name: v.name,
      district: v.district,
      state: v.state,
      latitude: v.latitude,
      longitude: v.longitude,
      population: v.population,
      risk_score: v.risk_score,
      risk_level: v.risk_level,
      relocation_priority: priority,
      vulnerability_multiplier: v.vulnerability_multiplier,
      top_factors: v.top_factors as any,
      low_confidence: v.low_confidence,
      recommended_site_id: v.recommended_site_id,
      // Optional relocation detail (null when no assignment exists)
      recommended_site_distance_km: v.recommended_site_distance_km ?? null,
      recommended_site_fit: v.recommended_site_fit ?? null,
      prediction_timestamp: new Date(v.prediction_timestamp),
      model_version: v.model_version,
    };
  });
  await bulkCreate(prisma.village, villageRows, "villages");

  console.log(`  ✓ ${villages.length} villages loaded`);
  if (Object.keys(vocabTranslated).length > 0) {
    console.log(
      `  [vocab] relocation_priority translated to VYOMA taxonomy: ` +
        Object.entries(vocabTranslated)
          .map(([from, n]) => `${from} → ${toVyomaPriority(from)} (${n})`)
          .join(", ")
    );
  }

  // --- Seed Relocation Sites ---
  const sitesRaw = readFileSync(sitesFile, "utf-8");
  const sites: any[] = JSON.parse(sitesRaw);

  console.log(`Loading ${sites.length} relocation sites from ${sitesFile}...`);

  const siteRows = sites.map((s) => ({
    site_id: s.site_id,
    name: s.name,
    district: s.district,
    state: s.state,
    latitude: s.latitude,
    longitude: s.longitude,
    suitability_score: s.suitability_score,
    total_capacity: s.total_capacity,
    occupied: s.occupied,
    available: s.available,
    infrastructure: s.infrastructure as any,
  }));
  await bulkCreate(prisma.relocationSite, siteRows, "sites");

  console.log(`  ✓ ${sites.length} relocation sites loaded`);
  console.log("\nSeed complete.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
