#!/usr/bin/env python3
"""
Generate the Relocation Sites dataset consumed by the VYOMA frontend schema.

WHAT THIS IS
------------
For every GREEN-zone village that is a carrying-capacity candidate we emit one
row with: geometry, suitability (0-100), total/available absorbable capacity,
current occupancy from the relocation plan, an `is_ideal` flag (top-tier
shortlist), and per-site infrastructure booleans derived from Census columns.This replaces the legacy, untraceable "236 IDEAL Relocation Sites" figure from
older README drafts. That number came from a `suitability_category` column that
is no longer generated by any script (62 of its 236 rows were even RED/ORANGE
villages — not valid relocation destinations). The tier is now DEFINED IN CODE:
    is_ideal  <=>  carrying_capacity_score >= 0.8   (446 of 12,211 eligible sites)
The threshold is a CLI argument (--min-ideal-score) so it stays auditable.

ELIGIBILITY (default --zone-filter green)
-----------------------------------------
The VYOMA export reports risk_level from the canonical susceptibility model,
so a destination site must itself be GREEN under that same model. The raw
carrying-capacity file (14,109 candidates) was computed against an older
historical zone snapshot and still contains villages that are RED (366) or
ORANGE (1,532) under the canonical model — we exclude them so we never
recommend relocating people into a zone the export itself flags as hazardous.
The eligible set is also written as relocation_capacity_pool.csv (carrying-
capacity schema) so relocation_planner.py --capacity plans against exactly
these sites. Use --zone-filter all to emit every measured candidate.

NOTES
-----
* site_id == the GREEN village's habitation_id (stable Census composite id),
  so `recommended_site_id` on villages references a real site row.
* occupied == sum of the populations of RED villages assigned to this site by
data/processed/relocation_plan.csv (red_habitation_id added to the plan;
  older files fall back to the planner's deterministic sort order).
* infrastructure booleans come from Census "Status A(1)/NA(2)" columns
  (1 == available) and "(Numbers)" columns (>0 == present); missing -> False.
* The full eligible register is emitted with an is_ideal flag rather than
  only the ideal subset, so no recommended_site_id ever dangles.

Outputs: data/processed/relocation_sites.csv and relocation_sites.json
"""

import argparse
import json
import os

import numpy as np
import pandas as pd

DATA_DIR = os.path.join('data', 'processed')
PRED_PATH = os.path.join(DATA_DIR, 'prediction_output.csv')
CAP_PATH = os.path.join(DATA_DIR, 'carrying_capacity.csv')
PLAN_PATH = os.path.join(DATA_DIR, 'relocation_plan.csv')

# Census infrastructure source columns (all guarded at runtime)
WATER_COLS = [
    'Tap Water-Treated (Status A(1)/NA(2))',
    'Tap Water Untreated (Status A(1)/NA(2))',
    'Covered Well (Status A(1)/NA(2))',
    'Uncovered  Well (Status A(1)/NA(2))',          # note double space in Census name
    'Hand Pump (Status A(1)/NA(2))',
    'Tube Wells/Borehole (Status A(1)/NA(2))',
    'Spring (Status A(1)/NA(2))',
    'River/Canal (Status A(1)/NA(2))',
    'Tank/Pond/Lake (Status A(1)/NA(2))',
]
ELECTRICITY_COLS = [
    'Power Supply For Domestic Use  (Status A(1)/NA(2))',   # double space in Census name
    'Power Supply For All Users (Status A(1)/NA(2))',
]
ROAD_COLS = [
    'National Highway (Status A(1)/NA(2))',
    'State Highway (Status A(1)/NA(2))',
    'Major District Road (Status A(1)/NA(2))',
    'Black Topped (pucca) Road (Status A(1)/NA(2))',
    'All Weather Road (Status A(1)/NA(2))',
    'Public Bus Service (Status A(1)/NA(2))',
]
# Proxy assumption (documented): a community centre is the closest Census proxy
# for a shelter/assembly building a relocated population could use.
SHELTER_COLS = ['Community Centre with/without TV (Status A(1)/NA(2))']
MEDICAL_COLS = [
    'Community Health Centre (Numbers)',
    'Primary Health Centre (Numbers)',
    'Primary Heallth Sub Centre (Numbers)',        # Census typo preserved
    'Dispensary (Numbers)',
    'Hospital Allopathic (Numbers)',
]
SANITATION_COLS = [
    'Closed Drainage (Status A(1)/NA(2))',
    'Open Drainage (Status A(1)/NA(2))',
    'Community Toilet Complex (including Bath) for General Public (Status A(1)/NA(2))',
]


def _status_available(df, cols):
    """True if ANY listed Census status column == 1 (A available)."""
    avail = pd.Series(False, index=df.index)
    for c in cols:
        if c in df.columns:
            avail = avail | (df[c] == 1).fillna(False)
    return avail


def _numbers_present(df, cols):
    """True if ANY listed Census Numbers column is > 0."""
    present = pd.Series(False, index=df.index)
    for c in cols:
        if c in df.columns:
            present = present | (pd.to_numeric(df[c], errors='coerce').fillna(0) > 0)
    return present


def _red_index_to_habitation(pred_df, plan_df):
    """Map relocation_plan red_village_id (0..N-1, assigned in the planner's
    deterministic sort order) back to habitation_id.

    relocation_planner.py selects sources as
        pred_df[RED | (ORANGE & priority_level=='HIGH')]
        .sort_values('risk_score', ascending=False)
        .reset_index(drop=True)
    and stores source.name as red_village_id. We replay the exact same selection
    against the same prediction_output.csv and verify the risk-score sequence
    matches the plan before trusting the mapping.
    """
    mask = (pred_df['predicted_risk_zone'] == 'RED') | (
        (pred_df['predicted_risk_zone'] == 'ORANGE') & (pred_df['priority_level'] == 'HIGH')
    )
    sources = pred_df[mask].sort_values('risk_score', ascending=False).reset_index(drop=True)

    plan_scores = pd.to_numeric(plan_df['red_risk_score'], errors='coerce').values
    src_scores = sources['risk_score'].round(6).values
    if len(plan_scores) != len(src_scores):
        raise ValueError(
            f"relocation_plan rows ({len(plan_scores)}) != replayed RED+HIGH-ORANGE "
            f"sources ({len(src_scores)}). Re-run scripts/relocation_planner.py on the "
            f"current prediction_output.csv before exporting."
        )
    mism = int((plan_scores != src_scores).sum())
    if mism > 0:
        raise ValueError(
            f"{mism} risk-score mismatches between relocation_plan.csv and the replayed "
            f"source order — relocation_plan.csv is stale. Re-run scripts/relocation_planner.py."
        )
    return dict(enumerate(sources['habitation_id']))


def main():
    parser = argparse.ArgumentParser(description='Generate relocation sites dataset')
    parser.add_argument('--min-ideal-score', type=float, default=0.8,
                        help='carrying_capacity_score threshold for is_ideal (default 0.8)')
    parser.add_argument('--zone-filter', choices=['green', 'all'], default='green',
                        help="Eligibility rule for destination sites. 'green' (default) = "
                             "only candidates that are GREEN under the CANONICAL "
                             "(susceptibility) model, so we never recommend relocating "
                             "people into a village the export itself labels RED/ORANGE. "
                             "'all' = every measured carrying-capacity candidate.")
    args = parser.parse_args()

    print("Loading prediction output, carrying capacity, and relocation plan...")
    pred_df = pd.read_csv(PRED_PATH, low_memory=False)
    cc = pd.read_csv(CAP_PATH)
    plan = pd.read_csv(PLAN_PATH)

    print(f"  {len(pred_df):,} villages, {len(cc):,} GREEN capacity candidates, "
          f"{len(plan):,} relocation-plan rows")

    # --- Attach habitation_id to RED sources --------------------------------
    # Preferred: relocation_plan.csv now carries red_habitation_id directly
    # (added to relocation_planner.py). Fallback for older files: replay the
    # planner's deterministic sort and verify the risk-score sequence matches.
    if 'red_habitation_id' in plan.columns:
        plan['red_habitation_id'] = plan['red_habitation_id'].fillna('')
    else:
        red_index_map = _red_index_to_habitation(pred_df, plan)
        plan['red_habitation_id'] = plan['red_village_id'].map(red_index_map)

    pred_by_hid = pred_df.set_index('habitation_id')
    def _pop_for(hid):
        if pd.isna(hid) or hid == '':
            return 0
        if hid in pred_by_hid.index:
            v = pred_by_hid.loc[hid, 'Total Population of Village']
            return int(v) if pd.notna(v) else 0
        return 0

    if 'red_population' not in plan.columns:
        plan['red_population'] = plan['red_habitation_id'].map(_pop_for)
    plan['red_population'] = plan['red_population'].fillna(0).astype(int)

    assigned = plan[plan['feasibility_flag'] == 'assigned'].copy()
    assigned['green_village_code'] = pd.to_numeric(
        assigned['green_village_id'], errors='coerce')
    print(f"  Assigned rows: {len(assigned):,} across "
          f"{assigned['green_village_code'].nunique():,} distinct sites")

    # Occupied population per assigned green site
    occupied_by_code = assigned.groupby('green_village_code')['red_population'].sum()

    # --- Join capacity candidates with census + site_id from prediction -------
    cc = cc.copy()
    cc['Village Code'] = cc['village_id'].astype(int)
    identity_cols = ['Village Code', 'habitation_id', 'Village Name',
                     'State Name', 'District Name', 'susceptibility_risk_zone',
                     'predicted_risk_zone']
    merged = cc.merge(pred_df[identity_cols], on='Village Code', how='left')

    # --- Canonical-zone eligibility filter -----------------------------------
    # The VYOMA export reports risk_level from the susceptibility model, so a
    # destination site must itself be GREEN under that same (canonical) model.
    # The raw carrying-capacity file was computed against an older historical
    # snapshot and contains villages that are now canonical RED/ORANGE.
    if args.zone_filter == 'green':
        elig = merged['susceptibility_risk_zone'] == 'GREEN'
        n_excluded = int((~elig).sum())
        print(f"\n  Zone filter '{args.zone_filter}': excluding {n_excluded:,} "
              f"candidates not GREEN under the canonical susceptibility model "
              f"(RED={(~elig & (merged['susceptibility_risk_zone'] == 'RED')).sum():,}, "
              f"ORANGE={(~elig & (merged['susceptibility_risk_zone'] == 'ORANGE')).sum():,})")
        merged = merged[elig].copy()
        # Also persist the eligible pool in carrying-capacity schema so
        # relocation_planner.py plans against exactly these sites.
        # Built from the ORIGINAL carrying-capacity frame (its schema already
        # matches pool_cols exactly) filtered to the eligible village_ids — NOT
        # by renaming columns on `merged`, which carries both the cc lowercase
        # state/district and the pred uppercase State/District Name and would
        # produce duplicate state/state.1, district/district.1 columns.
        pool_cols = ['village_id', 'village_name', 'state', 'district',
                     'latitude', 'longitude', 'buildable_land_ha',
                     'water_capacity_margin', 'infra_headroom_score',
                     'carrying_capacity_score', 'estimated_absorbable_population',
                     'limiting_factor', 'risk_zone']
        elig_ids = set(merged['village_id'])
        pool = cc[cc['village_id'].isin(elig_ids)][pool_cols]
        pool_path = os.path.join(DATA_DIR, 'relocation_capacity_pool.csv')
        pool.to_csv(pool_path, index=False)
        print(f"  Pool for relocation_planner --capacity saved: {pool_path} "
              f"({len(pool):,} eligible sites)")

    # Infrastructure booleans (1 == available / numbers > 0). Computed on the
    # prediction/census frame (indexed by Village Code) then mapped onto the
    # merged sites — so a renamed/missing Census column degrades to False
    # instead of crashing (several Census names contain stray spaces/typos).
    pred_idx = pred_df.set_index('Village Code')
    infra_src = pd.DataFrame({
        'water_supply': _status_available(pred_idx, WATER_COLS),
        'electricity': _status_available(pred_idx, ELECTRICITY_COLS),
        'road_access': _status_available(pred_idx, ROAD_COLS),
        'shelter': _status_available(pred_idx, SHELTER_COLS),
        'medical_facility': _numbers_present(pred_idx, MEDICAL_COLS),
        'sanitation': _status_available(pred_idx, SANITATION_COLS),
    })
    infra = pd.DataFrame(index=merged.index)
    for col in infra_src.columns:
        infra[col] = merged['Village Code'].map(infra_src[col]).fillna(False)

    total_capacity = pd.to_numeric(
        merged['estimated_absorbable_population'], errors='coerce').fillna(0).astype(int)
    occupied = merged['Village Code'].map(occupied_by_code).fillna(0).astype(int)

    sites = pd.DataFrame({
        'site_id': merged['habitation_id'],
        'name': merged['Village Name'],
        'district': merged['District Name'],
        'state': merged['State Name'],
        'latitude': merged['latitude'],
        'longitude': merged['longitude'],
        'suitability_score': np.round(pd.to_numeric(
            merged['carrying_capacity_score'], errors='coerce').fillna(0) * 100, 2),
        'total_capacity': total_capacity,
        'occupied': occupied,
        'available': np.maximum(total_capacity - occupied, 0).astype(int),
        'is_ideal': pd.to_numeric(merged['carrying_capacity_score'],
                                  errors='coerce').fillna(0) >= args.min_ideal_score,
        'water_supply': infra['water_supply'],
        'electricity': infra['electricity'],
        'road_access': infra['road_access'],
        'shelter': infra['shelter'],
        'medical_facility': infra['medical_facility'],
        'sanitation': infra['sanitation'],
    })

    n_ideal = int(sites['is_ideal'].sum())
    print(f"\n  Sites: {len(sites):,} rows, is_ideal (>= {args.min_ideal_score}): "
          f"{n_ideal:,} ({100*n_ideal/len(sites):.1f}% of candidates)")
    print(f"  Sites with occupied > 0: {(sites['occupied'] > 0).sum():,}")

    # Null-check: no dangling site references
    assigned_codes = set(assigned['green_village_code'].dropna().astype(int))
    site_codes = set(merged['Village Code'])
    dangling = assigned_codes - site_codes
    if dangling:
        print(f"  ⚠️  {len(dangling)} assigned target village codes not in capacity register")
    else:
        print(f"  ✅ every assigned target resolves to a site row")

    # --- Write CSV + JSON -----------------------------------------------------
    csv_path = os.path.join(DATA_DIR, 'relocation_sites.csv')
    sites.to_csv(csv_path, index=False)

    json_rows = []
    for _, r in sites.iterrows():
        json_rows.append({
            'site_id': r['site_id'],
            'name': r['name'],
            'district': r['district'],
            'state': r['state'],
            'latitude': float(r['latitude']) if pd.notna(r['latitude']) else None,
            'longitude': float(r['longitude']) if pd.notna(r['longitude']) else None,
            'suitability_score': float(r['suitability_score']),
            'total_capacity': int(r['total_capacity']),
            'occupied': int(r['occupied']),
            'available': int(r['available']),
            'is_ideal': bool(r['is_ideal']),
            'infrastructure': {
                'water_supply': bool(r['water_supply']),
                'electricity': bool(r['electricity']),
                'road_access': bool(r['road_access']),
                'shelter': bool(r['shelter']),
                'medical_facility': bool(r['medical_facility']),
                'sanitation': bool(r['sanitation']),
            },
        })

    json_path = os.path.join(DATA_DIR, 'relocation_sites.json')
    with open(json_path, 'w') as f:
        json.dump(json_rows, f, indent=1)
    print(f"\n  Saved: {csv_path}")
    print(f"  Saved: {json_path} ({len(json_rows):,} sites)")


if __name__ == '__main__':
    main()
